version: '3.8'
services:
  app:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm ci && npm run build && npm run preview -- --host 0.0.0.0 --port 3000"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    volumes:
      - .:/app 